# Generated by Django 5.2.3 on 2025-09-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pozo_latitud_pozo_longitud'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicion',
            options={'ordering': ['-fecha_hora']},
        ),
        migrations.AddIndex(
            model_name='medicion',
            index=models.Index(fields=['pozo', 'fecha_hora'], name='core_medici_pozo_id_3b6992_idx'),
        ),
    ]
