# Generated by Django 5.2.3 on 2025-07-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pozo',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pozo',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
